name: Run Tests
on: push
    
jobs:
    test:
        name: Test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macOS-latest, windows-latest]
        steps:
            - uses: actions/checkout@v4
            - name: checkout submodules
              run: git submodule update --init --recursive
        
            # Used to host cibuildwheel
            - uses: actions/setup-python@v4
        
            - name: Install cibuildwheel and other dependencies
              run: python -m pip install cibuildwheel==2.17.0 build wheel setuptools
        
            - name: Build sdist
              run: pipx run build --sdist --outdir wheelhouse
              if: runner.os == 'Windows'
        
            - name: Build wheels
              uses: pypa/cibuildwheel@v2.19.1 # run: python -m cibuildwheel --output-dir wheelhouse
              env:
                CIBW_ARCHS: auto64
                CIBW_ARCHS_MACOS: "x86_64"
                CIBW_ENVIRONMENT_MACOS: MACOSX_DEPLOYMENT_TARGET=11.0
                CIBW_ENVIRONMENT_LINUX: CXXFLAGS='-fconcepts'
                CIBW_BUILD_VERBOSITY_WINDOWS: 2
                CIBW_BEFORE_BUILD: ls -R pykingas # "! [ -d pykingas/fluids ] && cp -R fluids pykingas"
                CIBW_BUILD: "*cp310*"
              with:
                package-dir: .
                output-dir: "./wheelhouse"
                config-file: "{package}/pyproject.toml"
        
            - name: Upload Wheels
              uses: actions/upload-artifact@v4
              with:
                name: wheels-${{ matrix.os }}
                path: ./wheelhouse/*.whl
