name: Run Tests
on: push
    
jobs:
    test:
        name: Test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macos-latest, macos-12, ubuntu-latest]
        steps:
            - uses: actions/checkout@v4
            - name: checkout submodules
              run: git submodule update --init --recursive
        
            # Used to host cibuildwheel
            - uses: actions/setup-python@v4
        
            - uses: fortran-lang/setup-fortran@v1
              with:
                compiler: gcc
                version: 13
            
            - name: Build KineticGas
              run: |
                cd cpp/external/thermopack
                mkdir build
                cd build
                cmake ..
                make -j4 install
                cd ../../../..
                mkdir build
                cd build
                cmake ..
                make -j4 install
            
            - name: Run pytests
              run: |
                pip install .
                pip install pytest
                pytest tests/
