name: Run Tests
on: push
    
jobs:
    test:
        name: Test on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [macOS-latest, macOS-12, ubuntu-latest]
        env:
          THERMOPACK_DIR: thermopack-${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - name: checkout submodules
              run: git submodule update --init --recursive
        
            # Used to host cibuildwheel
            - uses: actions/setup-python@v4
        
            - name: Install thermopack
              run: |
                curl -L -o thermopack.zip https://github.com/vegardjervell/thermopack/releases/download/Latest-beta/thermopack-${{ matrix.os }}.zip
                unzip thermopack.zip
                export THERMOPACK_DIR=${PWD}/thermopack-${{ matrix.os }}/
                curl -L -o thermopack_whl.zip https://github.com/vegardjervell/thermopack/releases/download/Latest-beta/wheel-v2-${{ matrix.os }}.zip
                unzip thermopack_whl.zip
                pip install wheel-v2-${{ matrix.os }}/*
                
            - name: Build KineticGas
              run: |
                echo "THERMOPACK_DIR (GH_ENV) : ${{ env.THERMOPACK_DIR }} / (ENV) ${THERMOPACK_DIR}"
                export THERMOPACK_DIR=${PWD}/${{ env.THERMOPACK_DIR }}
                ls -R ${THERMOPACK_DIR}
                mkdir build
                cd build
                cmake ..
                make -j4 install
            
            - name: Run pytests
              run: |
                pip install .
                pip install pytest
                pytest tests/
